name: Test Package

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: golang
  
      - uses: actions/checkout@v2

      - run: |
          go get -t ./...

      - run: go test -v ./...